# Generated by Django 4.2.30 on 2026-04-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('wifi', 'WiFi'), ('sim', 'SIM'), ('ott', 'OTT')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('validity_days', models.IntegerField(choices=[(7, '7 Days'), (28, '28 Days'), (30, '30 Days'), (90, '90 Days'), (180, '180 Days'), (365, '365 Days')], default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speed_mbps', models.IntegerField(blank=True, help_text='Speed in Mbps', null=True)),
                ('data_limit_gb', models.IntegerField(blank=True, help_text='Data limit in GB, null=unlimited', null=True)),
                ('calls', models.CharField(blank=True, help_text='e.g. Unlimited, 100 mins', max_length=50, null=True)),
                ('sms', models.CharField(blank=True, help_text='e.g. 100 SMS, Unlimited', max_length=50, null=True)),
                ('mobile_data_gb', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('streams', models.IntegerField(blank=True, help_text='Simultaneous streams', null=True)),
                ('resolution', models.CharField(blank=True, help_text='e.g. HD, 4K', max_length=20, null=True)),
                ('platforms', models.CharField(blank=True, help_text='e.g. Web, Mobile, TV', max_length=200, null=True)),
            ],
            options={
                'ordering': ['plan_type', 'price'],
            },
        ),
    ]
